### ISSUE TITLE
导入bootstrapv4.1.1的css样式无法作用了

### ISSUE THREAD

**Issue by githubhao0705** [hylun/BootstrapPager#1]
而3.3.7的一切正常。（估计这么久了，作者应该不会更新了）

由于学习，需要从数据库查询数据并展示到前端，用了这个还蛮不错，蛮自动的。

正在研究中。谢谢作者。

**Comment by hylun** [comment]
感谢使用，我回头找时间研究一下适配 bootstrapv4.1.1

**Comment by githubhao0705** [comment]
首先感谢作者你的回复。

因为我才接触前端，写得头晕晕的，我整理一下，看行不行，不行再把代码贴给你吧，真是麻烦你了。

**Comment by hylun** [comment]
试一下新版本，做了兼容
